g4-common: fix build errors + convert to Blueprint
during build of A12 the following errors occured:

> FAILED: out/target/common/obj/JAVA_LIBRARIES/com.qti.location.sdk_intermediates/enforce_uses_libraries.status
> /bin/bash -c "(rm -f out/target/common/obj/JAVA_LIBRARIES/com.qti.location.sdk_intermediates/enforce_uses_libraries.status ) && (build/soong/scripts/manifest_check.py    --enforce-uses-libraries        --enforce-uses-libraries-status out/target/common/obj/JAVA_LIBRARIES/com.qti.location.sdk_intermediates/enforce_uses_libraries.status       --aapt out/host/linux-x86/bin/aapt                                      vendor/lge/g4-common/proprietary/framework/com.qti.location.sdk.jar )"
> error: not well-formed (invalid token): line 1, column 2
> [ 67% 86260/128675] Verifying uses-libraries: vendor/lge/g4-common/proprietary/framework/com.qti.snapdragon.sdk.display.jar
> FAILED: out/target/common/obj/JAVA_LIBRARIES/com.qti.snapdragon.sdk.display_intermediates/enforce_uses_libraries.status
> /bin/bash -c "(rm -f out/target/common/obj/JAVA_LIBRARIES/com.qti.snapdragon.sdk.display_intermediates/enforce_uses_libraries.status ) && (build/soong/scripts/manifest_check.py          --enforce-uses-libraries        --enforce-uses-libraries-status out/target/common/obj/JAVA_LIBRARIES/com.qti.snapdragon.sdk.display_intermediates/enforce_uses_libraries.status     --aapt out/host/linux-x86/bin/aapt                                      vendor/lge/g4-common/proprietary/framework/com.qti.snapdragon.sdk.display.jar )"
> error: not well-formed (invalid token): line 1, column 2
> [ 67% 86261/128675] Verifying uses-libraries: vendor/lge/g4-common/proprietary/framework/izat.xt.srv.jar
> FAILED: out/target/common/obj/JAVA_LIBRARIES/izat.xt.srv_intermediates/enforce_uses_libraries.status
> /bin/bash -c "(rm -f out/target/common/obj/JAVA_LIBRARIES/izat.xt.srv_intermediates/enforce_uses_libraries.status ) && (build/soong/scripts/manifest_check.py     --enforce-uses-libraries        --enforce-uses-libraries-status out/target/common/obj/JAVA_LIBRARIES/izat.xt.srv_intermediates/enforce_uses_libraries.status        --aapt out/host/linux-x86/bin/aapt                                      vendor/lge/g4-common/proprietary/framework/izat.xt.srv.jar )"
> error: not well-formed (invalid token): line 1, column 2
> [ 67% 86262/128675] Verifying uses-libraries: vendor/lge/g4-common/proprietary/framework/qcnvitems.jar
> FAILED: out/target/common/obj/JAVA_LIBRARIES/qcnvitems_intermediates/enforce_uses_libraries.status
> /bin/bash -c "(rm -f out/target/common/obj/JAVA_LIBRARIES/qcnvitems_intermediates/enforce_uses_libraries.status ) && (build/soong/scripts/manifest_check.py       --enforce-uses-libraries        --enforce-uses-libraries-status out/target/common/obj/JAVA_LIBRARIES/qcnvitems_intermediates/enforce_uses_libraries.status          --aapt out/host/linux-x86/bin/aapt                                      vendor/lge/g4-common/proprietary/framework/qcnvitems.jar )"
> error: not well-formed (invalid token): line 1, column 2

REASON

https://android.googlesource.com/platform/build/+/refs/heads/master/Changes.md#dexpreopt-starts-enforcing-checks-for-java-modules

WORKAROUND

either specify RELAX_USES_LIBRARY_CHECK=true as an environment variable OR specify PRODUCT_BROKEN_VERIFY_USES_LIBRARIES := true

FIX

ofc that is just a workaround and should be avoided. the REAL fix is doing what the changes.md says and fixing the module definitions in vendor/lge.
This is done by this commit in 3 steps: a) converting into blueprint and b) removing incompat flags c) adding system_ext_specific definiton.
The above workaround is not needed anymore.

Change-Id: Ia4fac61780f89be59fc187bb924da7739bab9c2c
Signed-off-by: steadfasterX <steadfasterX@gmail.com>